# Generated by Django 5.2.6 on 2025-09-08 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraseMotivacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Frase motivacional')),
            ],
            options={
                'verbose_name': 'Frase Motivacional',
                'verbose_name_plural': 'Frases Motivacionais',
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do psicólogo')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail do psicólogo')),
                ('registro_crp', models.CharField(max_length=20, verbose_name='Registro CRP')),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
            },
        ),
        migrations.CreateModel(
            name='FraseFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicionada', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('frase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.frasemotivacional')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail do usuário')),
                ('senha', models.CharField(max_length=10, verbose_name='Senha do usuário')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuário Comum'), ('psicologo', 'Psicólogo')], default='usuario', max_length=20)),
                ('psicologo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.psicologo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='MetaTerapeutica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da meta')),
                ('status', models.CharField(max_length=20, verbose_name='Status da meta')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.psicologo', verbose_name='Meta definida pelo psicólogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Meta para o usuário')),
            ],
            options={
                'verbose_name': 'Meta Terapêutica',
                'verbose_name_plural': 'Metas Terapêuticas',
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('conteudo', models.TextField(default='Sem conteúdo')),
                ('emocao', models.CharField(max_length=5)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CheckinEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humor', models.CharField(max_length=50, verbose_name='Humor do usuário')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do check-in')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Check-in do usuário')),
            ],
            options={
                'verbose_name': 'Check-in Emocional',
                'verbose_name_plural': 'Check-ins Emocionais',
            },
        ),
    ]
