# Generated by Django 5.2.4 on 2025-07-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraseMotivacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Frase motivacional')),
            ],
            options={
                'verbose_name': 'Frase Motivacional',
                'verbose_name_plural': 'Frases Motivacionais',
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do psicólogo')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail do psicólogo')),
                ('registro_crp', models.CharField(max_length=20, verbose_name='Registro CRP')),
            ],
            options={
                'verbose_name': 'Psicólogo',
                'verbose_name_plural': 'Psicólogos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='E-mail do usuário')),
                ('senha', models.CharField(max_length=10, verbose_name='Senha do usuário')),
                ('data_nasc', models.DateField(verbose_name='Data de nascimento')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='MetaTerapeutica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição da meta')),
                ('status', models.CharField(max_length=20, verbose_name='Status da meta')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.psicologo', verbose_name='Meta definida pelo psicólogo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Meta para o usuário')),
            ],
            options={
                'verbose_name': 'Meta Terapêutica',
                'verbose_name_plural': 'Metas Terapêuticas',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Conteúdo da mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='app.usuario')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='app.usuario')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
            },
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto do diário')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Diário do usuário')),
            ],
            options={
                'verbose_name': 'Registro de Diário',
                'verbose_name_plural': 'Registros de Diário',
            },
        ),
        migrations.CreateModel(
            name='CheckinEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humor', models.CharField(max_length=50, verbose_name='Humor do usuário')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do check-in')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Check-in do usuário')),
            ],
            options={
                'verbose_name': 'Check-in Emocional',
                'verbose_name_plural': 'Check-ins Emocionais',
            },
        ),
    ]
