# Generated by Django 5.2.4 on 2025-08-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuário Comum'), ('psicologo', 'Psicólogo')], default='usuario', max_length=20),
        ),
    ]
