# Generated by Django 5.2.6 on 2025-10-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='mensagem',
        ),
    ]
