# Generated by Django 5.2.4 on 2025-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_psicologo',
            field=models.BooleanField(default=False),
        ),
    ]
