# Generated by Django 5.2.4 on 2025-08-07 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_is_psicologo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_psicologo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='psicologo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.psicologo'),
        ),
    ]
