# Generated by Django 5.2.6 on 2025-09-06 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_frasefavorita_notificacao_delete_mensagem'),
        ('app', '0004_remove_usuario_is_psicologo_usuario_psicologo'),
    ]

    operations = [
    ]
